src/routes/app_route.py
from flask import *
from controllers.videoFeed import VideoFeed
from models.facecam import Facecam

app_api = Blueprint("app_api", __name__)


@app_api.route("/")
def index():
    return render_template("index.html")

@app_api.route("/canvas")
def canvas():
    return render_template("canvas.html")

@app_api.route("/video")
def videoFeed():
    return Response(VideoFeed.gen(Facecam()), mimetype='multipart/x-mixed-replace; boundary=frame')

@app_api.route("/pre/video")
def preVideoFeed():
    return Response(VideoFeed.pre_gen(Facecam()), mimetype='multipart/x-mixed-replace; boundary=frame')

src/templates/canvas.html
<!-- @format -->

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			rel="icon"
			href="https://s3.amazonaws.com/www.miniroom.online/images/favicon.ico"
			type="image/x-icon" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
			rel="stylesheet" />
		<link
			href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
			rel="stylesheet" />
		<link rel="stylesheet" href="../static/css/common.css" />
		<link rel="stylesheet" href="../static/css/canvas.css" />
		<title>Mini Room</title>
	</head>
	<body>
		<header class="center">
			<nav class="navbar navbar-grid">
				<div>
					<a class="navbar-brand center" href="/">
						<img
							src="https://s3.amazonaws.com/www.miniroom.online/images/logo.png"
							alt=""
							class="d-inline-block align-text-top" />
						<span class="logo">Mini Room</span>
					</a>
				</div>
				<h3 class="center">Hand Tracking Canvas</h3>
			</nav>
		</header>
		<div id="canvasContainer" class="canvas-container">
			<div class="palette-container">
				<div class="palette center">
					<div></div>
				</div>
				<div class="palette center">
					<div class="red"></div>
				</div>
				<div class="palette center">
					<div class="blue"></div>
				</div>
				<div class="palette center">
					<div class="green"></div>
				</div>
				<div class="palette center">
					<div class="eraser">
						<img class="eraser-img" src="../static/images/eraser.png" />
					</div>
				</div>
			</div>
			<div class="shape-container">
				<div class="shape center">
					<div class="draw">
						<img class="draw-img" src="../static/images/draw.png" />
					</div>
				</div>
				<div class="shape center">
					<div class="circle"></div>
				</div>
				<div class="shape center">
					<div class="rectangle"></div>
				</div>
				<div class="shape center">
					<div class="line"></div>
				</div>
			</div>
			<img
				id="canvasImg"
				class="canvas-image"
				src="{{ url_for('app_api.videoFeed') }}" />
		</div>
	</body>
</html>

src/templates/index.html
<!-- @format -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      href="https://s3.amazonaws.com/www.miniroom.online/images/favicon.ico"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="../static/css/common.css" />
    <link rel="stylesheet" href="../static/css/index.css" />
    <title>Mini Room</title>
  </head>
  <body>
    <header class="center">
      <nav class="navbar navbar-grid">
        <div>
          <a class="navbar-brand center" href="/">
            <img
              src="https://s3.amazonaws.com/www.miniroom.online/images/logo.png"
              alt=""
              class="d-inline-block align-text-top"
            />
            <span class="logo">Mini Room</span>
          </a>
        </div>
        <h3 class="center">Hand Tracking Canvas</h3>
      </nav>
    </header>
    <section class="hero center">
      <div class="hero-content">
        <div class="hero-img-container">
          <img class="hero-img" src="../static/images/hero-img_index.png" />
        </div>
        <div class="start-btn-container center">
          <a href="/canvas"
            ><button type="button" class="btn start-btn">Get Started</button></a
          >
          <img src="{{ url_for('app_api.preVideoFeed') }}" class="none" />
        </div>
      </div>
    </section>
  </body>
</html>